basePath: /
definitions:
  models.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  models.UpdatePreferencesRequest:
    properties:
      ageRange:
        type: string
      distance:
        type: integer
      genderPreference:
        type: string
    type: object
  models.UpdateProfileRequest:
    properties:
      ageRange:
        type: string
      dateOfBirth:
        type: string
      distance:
        type: integer
      firstName:
        type: string
      gender:
        type: string
      genderPreference:
        type: string
      interestedIn:
        type: string
      interests:
        items:
          type: string
        type: array
      latitude:
        type: number
      longitude:
        type: number
      lookingFor:
        type: string
      photos:
        items:
          type: string
        type: array
      profilePictureURL:
        type: string
      sexualOrientation:
        type: string
    type: object
  models.User:
    properties:
      ageRange:
        type: string
      bio:
        type: string
      createdAt:
        type: string
      dateOfBirth:
        type: string
      distance:
        type: integer
      email:
        type: string
      firstName:
        type: string
      gender:
        type: string
      genderPreference:
        type: string
      id:
        description: gorm.Model
        type: integer
      interestedIn:
        type: string
      interests:
        items:
          type: string
        type: array
      latitude:
        type: number
      longitude:
        type: number
      lookingFor:
        type: string
      photos:
        items:
          type: string
        type: array
      profilePictureURL:
        type: string
      sexualOrientation:
        type: string
      updatedAt:
        type: string
    type: object
host: campuscupid-backend.onrender.com
info:
  contact:
    email: support@campuscupid.com
    name: API Support
  description: This is the backend API for the CampusCupid dating app.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: CampusCupid API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Authenticate a user and return a JWT token
      parameters:
      - description: User login credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login a user
      tags:
      - users
  /matches/{user_id}:
    get:
      consumes:
      - application/json
      description: Retrieve a list of potential matches based on user preferences
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: integer
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Items per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get potential matches
      tags:
      - matchmaking
  /preferences/{user_id}:
    put:
      consumes:
      - application/json
      description: Update the user's age range, distance, and gender preference
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: integer
      - description: User Preferences
        in: body
        name: preferences
        required: true
        schema:
          $ref: '#/definitions/models.UpdatePreferencesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Update user preferences
      tags:
      - users
  /profile/{user_id}:
    get:
      consumes:
      - application/json
      description: Get the profile details of a user using the user_id
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Get user profile by user_id
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update profile details such as bio, interests, and preferences
        (excluding ID, Username, Email, Password)
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: integer
      - description: Updated profile details
        in: body
        name: profile
        required: true
        schema:
          $ref: '#/definitions/models.UpdateProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Update user profile by user_id
      tags:
      - users
swagger: "2.0"
